name: myaction
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt update
          sudo apt install -y build-essential
          sudo apt install -y g++-10
          sudo ln -s $(which g++-10) /usr/local/g++
      - uses: actions/checkout@v2
      - name: test
        run: |
          g++ -std=c++20 source.cpp 
          ./a.out
