name: myaction
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt update
          sudo apt install -y build-essential
          sudo apt install -y g++-10
          g++-10 --version
      - uses: actions/checkout@v2
      - name: test
        run: |
          g++-10 source.cpp 
          ./a.out
